TOPLEVEL_LANG = verilog
VERILOG_SOURCES = secret_entrance_part1.v
TOPLEVEL = secret_entrance_part1
MODULE = test_day_1

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
