TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_1.v
TOPLEVEL = day_1
MODULE = test_day_1

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
