TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_2.v
TOPLEVEL = day_2
MODULE = test_day_2

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
