TOPLEVEL_LANG = verilog
VERILOG_SOURCES = cafeteria_part2.v 
TOPLEVEL = cafeteria_part2
MODULE = test_day_5

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
