TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_9.v 
TOPLEVEL = day_9
MODULE = test_day_9

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
