TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_5.v 
TOPLEVEL = day_5
MODULE = test_day_5

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
