TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_10.v 
TOPLEVEL = day_10
MODULE = test_day_10

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
