TOPLEVEL_LANG = verilog
VERILOG_SOURCES = christmas_tree_farm.v 
TOPLEVEL = christmas_tree_farm
MODULE = test_day_12

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
