TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_12.v 
TOPLEVEL = day_12
MODULE = test_day_12

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
