TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_11.v 
TOPLEVEL = day_11
MODULE = test_day_11

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
