TOPLEVEL_LANG = verilog
VERILOG_SOURCES = gift_shop_part1.v
TOPLEVEL = gift_shop_part1
MODULE = test_day_2

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
