TOPLEVEL_LANG = verilog
VERILOG_SOURCES = trash_compactor_part1.v 
TOPLEVEL = trash_compactor_part1
MODULE = test_day_6

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
