TOPLEVEL_LANG = verilog
VERILOG_SOURCES = lobby_part1.v find_highest.v
TOPLEVEL = lobby_part1
MODULE = test_day_3

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
