TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_3.v
TOPLEVEL = day_3
MODULE = test_day_3

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
