TOPLEVEL_LANG = verilog
VERILOG_SOURCES = playground_part1.v min5.v
TOPLEVEL = playground_part1
MODULE = test_day_8

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
