TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_6.v 
TOPLEVEL = day_6
MODULE = test_day_6

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
