TOPLEVEL_LANG = verilog
VERILOG_SOURCES = day_4.v 
TOPLEVEL = day_4
MODULE = test_day_4

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
