TOPLEVEL_LANG = verilog
VERILOG_SOURCES = printing_department_part1.v 
TOPLEVEL = printing_department_part1
MODULE = test_day_4

COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

include $(shell cocotb-config --makefiles)/Makefile.sim
